# Generated by Django 5.2.1 on 2025-06-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='sexo',
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mascotas/'),
        ),
    ]
