# Generated by Django 5.2.1 on 2025-06-02 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialApp', '0002_remove_mascota_propietario_remove_mascota_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historialApp.propietario'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas_fotos/'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100),
        ),
    ]
